# This secret is still under testing, please do not use it except for experiment
- secret:
    name: heat_doker_login
    data:
      user: !encrypted/pkcs1-oaep
        - hmhTlr42RFyIu+Bjlu7AJqYeEcs4Qi8XSvavFzXohI+tmqskWzCVTynqVs6H+FEZpoZ/d
          QGrjVr8oXgjrNQgcWDENQc3P+h6hwFhs2FncISq6dLxJcwqJwmBLUz4dGXh++0twccK7A
          dkBzmF3pHURFydCtqT33PfHuYvrSHHwmiZySyjRp4vvRTZa3LzuXi//ILYC+FARwvjzv8
          yiISfE32kOGbZsDdjy2vqjROd6zfCxJ9i+v0eis0euOnLwC7o2wZi/DDG+Ec4X1y11tPM
          utxaEG9MGGorsdvccwlU96rZ1CAp0QGrAAjNVFt40TWvMQlhb8RS1iGdu+coy2s0FP9Zf
          teWG0ISNNAOyeKXz8M/eK+1mVBIiFtGsicnUnnc8Ic1NkXt6AjCDbJdM6nujlTLt++qqf
          Kzmi0wxk5CXV+gghxpwrV2WbW4q9OyQnparPMdGdZWAc6/0PwFDsR/tzJ2vy20OeXobTq
          n7ggnv/QTM1KX25DRKiMty87tINdWi63ljsOW4dvAu916o+bH7ObZEcrjqnIT/XqXNzfP
          vnAF+r7lIQg9Zl0e58cgs8vwJN+AiIUKR7Zy6Y+BEckpj9uPDUURM7lJhpSMDkzMTOa7A
          Wyxrz6MTOlo7fIrts5EEHgh5jsFKXgHQ/qXxZ2pBvUlpDxG+EDiOGfU0U8SV3c=
      password: !encrypted/pkcs1-oaep
        - J/J0uSTI2JQp4q79vckx3SEMAakLd113EE46hAShH5uDQVbKIbICLbClqPvPbCycyxVkV
          zbUSNEX6nBbc8kLEwMXD0MQpsY2heOhcKWEZxzLiMQ+GpeDhc7cBc6tvD+sTiz670Z/Vl
          Wj1JRePrpwqUwooSbosU2iFSDotUR63fzsXzS2xl1cWQrnz/ff5tMZsGBAgqPY+Udgvke
          qTI/gQNOfJ9duR0HzUuSbGOQXpyL5zmx9DjBcIbkkKVhrztUZt7o1ehg0K6sQV/xtz9Is
          0QRivhzvRTB32UNZTPSyuNPAU/nMkCVIDyNoHX3jJSUSP9Fn2IsF+qMQsryZN70TOn4Nb
          1AgUITjUHucvv5LEqd7/qDCa8wOCit2iBpSFCQ6O+6bSBJvWxfO+fSPeaeQtbbk+ZWehG
          n1i3vc8ionkz2t33sQKxPifpXJmyBkd6/+Kfk1x3KNKPCjs6KvtUZvwbeRgM36JVbTUKc
          un2maaWtY98lFb3XhA61wurhx7J7FGtHSycuqzLLub8COfYNuDxClpBxBvECZtSUkFb+Z
          Q6XUvVQQswozSDBPeGMrAwirGO7zBS1+mBCT80uNs1vcApTwIKw72HLvAPirW3xbxnj0t
          6fYy5mV+gtgdYe1yFQPinGy3y6QE4av0OUaouUGJnfV/yv3w5+lfgj/7/becJQ=

- project:
    templates:
      - openstack-python3-ussuri-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - openstack-lower-constraints-jobs
